const CONTEXT_NAME = 'OLYMPIC'

const actions = {
    OLYMPIC_GET_LIST: `${CONTEXT_NAME}_GET_LIST`,
    OLYMPIC_REQUEST_GET_LIST: `${CONTEXT_NAME}_REQUEST_GET_LIST`,
    OLYMPIC_REQUEST_SAVE_DATA: `${CONTEXT_NAME}_REQUEST_SAVE_DATA`,
    OLYMPIC_SAVE_DATA: `${CONTEXT_NAME}_SAVE_DATA`
}

export { actions }
